
#node_js: stable
 
# S: Build Lifecycle
#install:
 # - npm install
language: node_js
node_js:
  - "0.12"
install:
  - npm install hexo-cli -g
  - npm install hexo --save
  - npm install
 
#before_script:
 # - npm install -g gulp
 
script:
  - hexo g
 
after_script:
  - cd ./public
  - git init
  - git config user.name "Magicer"
  - git config user.email "magicer_zhang@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle
 
branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/Magicer/MagicerXYZ.git